/**
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for license
information.
Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.analysisservices.implementation;

import com.microsoft.azure.AzureEnvironment;
import com.microsoft.azure.AzureResponseBuilder;
import com.microsoft.azure.credentials.AzureTokenCredentials;
import com.microsoft.azure.management.resources.fluentcore.arm.AzureConfigurable;
import com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl;
import com.microsoft.azure.management.resources.fluentcore.arm.implementation.Manager;
import com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor;
import com.microsoft.azure.serializer.AzureJacksonAdapter;
import com.microsoft.rest.RestClient;

/**
 * Entry point to Azure AnalysisServices resource management.
 */
@Beta(Beta.SinceVersion.V1_2_0)
public final class AnalysisServicesManager extends Manager<AnalysisServicesManager, AnalysisServicesManagementClientImpl> {
    /**
    * Get a Configurable instance that can be used to create AnalysisServicesManager with optional configuration.
    *
    * @return the instance allowing configurations
    */
    public static Configurable configure() {
        return new AnalysisServicesManager.ConfigurableImpl();
    }
    /**
    * Creates an instance of AnalysisServicesManager that exposes AnalysisServices resource management API entry points.
    *
    * @param credentials the credentials to use
    * @param subscriptionId the subscription UUID
    * @return the AnalysisServicesManager
    */
    public static AnalysisServicesManager authenticate(AzureTokenCredentials credentials, String subscriptionId) {
        return new AnalysisServicesManager(new RestClient.Builder()
            .withBaseUrl(credentials.environment(), AzureEnvironment.Endpoint.RESOURCE_MANAGER)
            .withCredentials(credentials)
            .withSerializerAdapter(new AzureJacksonAdapter())
            .withResponseBuilderFactory(new AzureResponseBuilder.Factory())
            .withInterceptor(new ProviderRegistrationInterceptor(credentials))
            .build(), subscriptionId);
    }
    /**
    * Creates an instance of AnalysisServicesManager that exposes AnalysisServices resource management API entry points.
    *
    * @param restClient the RestClient to be used for API calls.
    * @param subscriptionId the subscription UUID
    * @return the AnalysisServicesManager
    */
    public static AnalysisServicesManager authenticate(RestClient restClient, String subscriptionId) {
        return new AnalysisServicesManager(restClient, subscriptionId);
    }
    /**
    * The interface allowing configurations to be set.
    */
    public interface Configurable extends AzureConfigurable<Configurable> {
        /**
        * Creates an instance of AnalysisServicesManager that exposes AnalysisServices management API entry points.
        *
        * @param credentials the credentials to use
        * @param subscriptionId the subscription UUID
        * @return the interface exposing storage management API entry points that work across subscriptions
        */
        AnalysisServicesManager authenticate(AzureTokenCredentials credentials, String subscriptionId);
    }
    /**
    * The implementation for Configurable interface.
    */
    private static final class ConfigurableImpl extends AzureConfigurableImpl<Configurable> implements Configurable {
        public AnalysisServicesManager authenticate(AzureTokenCredentials credentials, String subscriptionId) {
           return AnalysisServicesManager.authenticate(buildRestClient(credentials), subscriptionId);
        }
     }
    private AnalysisServicesManager(RestClient restClient, String subscriptionId) {
        super(
            restClient,
            subscriptionId,
            new AnalysisServicesManagementClientImpl(restClient).withSubscriptionId(subscriptionId));
    }
}
