/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.analysisservices.implementation;

import com.microsoft.azure.management.analysisservices.ResourceSku;
import java.util.Map;
import com.microsoft.azure.management.analysisservices.ServerAdministrators;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * Provision request specification.
 */
@JsonFlatten
public class AnalysisServicesServerUpdateParametersInner {
    /**
     * The SKU of the Analysis Services resource.
     */
    @JsonProperty(value = "sku")
    private ResourceSku sku;

    /**
     * Key-value pairs of additional provisioning properties.
     */
    @JsonProperty(value = "tags")
    private Map<String, String> tags;

    /**
     * A collection of AS server administrators.
     */
    @JsonProperty(value = "properties.asAdministrators")
    private ServerAdministrators asAdministrators;

    /**
     * The container URI of backup blob.
     */
    @JsonProperty(value = "properties.backupBlobContainerUri")
    private String backupBlobContainerUri;

    /**
     * Get the sku value.
     *
     * @return the sku value
     */
    public ResourceSku sku() {
        return this.sku;
    }

    /**
     * Set the sku value.
     *
     * @param sku the sku value to set
     * @return the AnalysisServicesServerUpdateParametersInner object itself.
     */
    public AnalysisServicesServerUpdateParametersInner withSku(ResourceSku sku) {
        this.sku = sku;
        return this;
    }

    /**
     * Get the tags value.
     *
     * @return the tags value
     */
    public Map<String, String> tags() {
        return this.tags;
    }

    /**
     * Set the tags value.
     *
     * @param tags the tags value to set
     * @return the AnalysisServicesServerUpdateParametersInner object itself.
     */
    public AnalysisServicesServerUpdateParametersInner withTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the asAdministrators value.
     *
     * @return the asAdministrators value
     */
    public ServerAdministrators asAdministrators() {
        return this.asAdministrators;
    }

    /**
     * Set the asAdministrators value.
     *
     * @param asAdministrators the asAdministrators value to set
     * @return the AnalysisServicesServerUpdateParametersInner object itself.
     */
    public AnalysisServicesServerUpdateParametersInner withAsAdministrators(ServerAdministrators asAdministrators) {
        this.asAdministrators = asAdministrators;
        return this;
    }

    /**
     * Get the backupBlobContainerUri value.
     *
     * @return the backupBlobContainerUri value
     */
    public String backupBlobContainerUri() {
        return this.backupBlobContainerUri;
    }

    /**
     * Set the backupBlobContainerUri value.
     *
     * @param backupBlobContainerUri the backupBlobContainerUri value to set
     * @return the AnalysisServicesServerUpdateParametersInner object itself.
     */
    public AnalysisServicesServerUpdateParametersInner withBackupBlobContainerUri(String backupBlobContainerUri) {
        this.backupBlobContainerUri = backupBlobContainerUri;
        return this;
    }

}
