/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.analysisservices.implementation;

import java.util.List;
import com.microsoft.azure.management.analysisservices.ResourceSku;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An object that represents enumerating SKUs for new resources.
 */
public class SkuEnumerationForNewResourceResultInner {
    /**
     * The collection of available SKUs for new resources.
     */
    @JsonProperty(value = "value")
    private List<ResourceSku> value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<ResourceSku> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the SkuEnumerationForNewResourceResultInner object itself.
     */
    public SkuEnumerationForNewResourceResultInner withValue(List<ResourceSku> value) {
        this.value = value;
        return this;
    }

}
