/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.analysisservices;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the SKU name and Azure pricing tier for Analysis Services
 * resource.
 */
public class ResourceSku {
    /**
     * Name of the SKU level.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The name of the Azure pricing tier to which the SKU applies. Possible
     * values include: 'Development', 'Basic', 'Standard'.
     */
    @JsonProperty(value = "tier")
    private SkuTier tier;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ResourceSku object itself.
     */
    public ResourceSku withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the tier value.
     *
     * @return the tier value
     */
    public SkuTier tier() {
        return this.tier;
    }

    /**
     * Set the tier value.
     *
     * @param tier the tier value to set
     * @return the ResourceSku object itself.
     */
    public ResourceSku withTier(SkuTier tier) {
        this.tier = tier;
        return this;
    }

}
