/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.analysisservices;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An array of administrator user identities.
 */
public class ServerAdministrators {
    /**
     * An array of administrator user identities.
     */
    @JsonProperty(value = "members")
    private List<String> members;

    /**
     * Get the members value.
     *
     * @return the members value
     */
    public List<String> members() {
        return this.members;
    }

    /**
     * Set the members value.
     *
     * @param members the members value to set
     * @return the ServerAdministrators object itself.
     */
    public ServerAdministrators withMembers(List<String> members) {
        this.members = members;
        return this;
    }

}
